workflows:
  android-workflow:
    name: Build Android
    max_build_duration: 60
    environment:
      vars:
        ANDROID_HOME: $ANDROID_SDK_ROOT
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    scripts:
      - name: Set permission
        script: chmod +x gradlew
      - name: Build APK
        script: ./gradlew assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/apk/**/*.apk
