workflows:
  android-workflow:
    name: Build Android
    max_build_duration: 120
    environment:
      vars:
        ANDROID_HOME: $ANDROID_SDK_ROOT
        GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx1024m
    scripts:
      - name: Build APK
        script: gradle assembleDebug --stacktrace --no-daemon -Dorg.gradle.jvmargs=-Xmx1024m
    artifacts:
      - app/build/outputs/apk/**/*.apk
