workflows:
  android-workflow:
    name: Build Android
    environment:
      vars:
        ANDROID_HOME: /opt/android-sdk
    scripts:
      - name: Set permission
        script: chmod +x gradlew
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk